// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RulesEngineEditorServer.Data;

#nullable disable

namespace RulesEngineEditorServer.Migrations
{
    [DbContext(typeof(RulesDbContext))]
    [Migration("20250511042103_InitSchema")]
    partial class InitSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("RulesEngineEditorServer.Models.RulesWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RulesWorkflows");
                });
#pragma warning restore 612, 618
        }
    }
}
